{{- if .Values.exporters.kubeStateMetrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "continuous-monitoring.fullname" . }}-kube-state-metrics
  labels:
    {{- include "continuous-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-state-metrics
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "continuous-monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kube-state-metrics
{{- end }}
