{{- if and .Values.datasources.enabled .Values.datasources.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "continuous-monitoring.fullname" . }}-prometheus
  labels:
    {{- include "continuous-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: datasources
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "continuous-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: prometheus
  template:
    metadata:
      labels:
        {{- include "continuous-monitoring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: prometheus
    spec:
      containers:
        - name: prometheus
          image: "{{ include "continuous-monitoring.image" (list .Values.datasources.prometheus.image.repository .Values.datasources.prometheus.image.tag .Values.datasources.prometheus.image.digest) }}"
          imagePullPolicy: {{ .Values.datasources.prometheus.image.pullPolicy }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.enable-lifecycle"
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /prometheus
          {{- with .Values.datasources.prometheus.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "continuous-monitoring.fullname" . }}-prometheus-config
        - name: data
          emptyDir: {}
      {{- with .Values.datasources.prometheus.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.datasources.prometheus.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.datasources.prometheus.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
