{{- if and .Values.databases.mysql.enabled (not .Values.databases.mysql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "continuous-monitoring.fullname" . }}-mysql-credentials
  labels:
    {{- include "continuous-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
    app.kubernetes.io/part-of: databases
type: Opaque
stringData:
  username: {{ .Values.databases.mysql.auth.username }}
  password: {{ .Values.databases.mysql.auth.password }}
  database: {{ .Values.databases.mysql.auth.database }}
  dsn: {{ .Values.databases.mysql.auth.username }}:{{ .Values.databases.mysql.auth.password }}@tcp(127.0.0.1:{{ .Values.databases.mysql.service.port }})/{{ .Values.databases.mysql.auth.database }}
{{- end }}
