{{- if and .Values.datasources.enabled .Values.datasources.loki.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "continuous-monitoring.fullname" . }}-loki-config
  labels:
    {{- include "continuous-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
    app.kubernetes.io/part-of: datasources

data:
  loki.yaml: |
{{ tpl (.Files.Get "files/loki/loki.yaml") . | indent 4 }}
{{- end }}
