{{- if and .Values.datasources.enabled .Values.datasources.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "continuous-monitoring.fullname" . }}-loki
  labels:
    {{- include "continuous-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
    app.kubernetes.io/part-of: datasources
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
  selector:
    {{- include "continuous-monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: loki
{{- end }}
