apiVersion: v2
name: continuous-monitoring
description: Helm chart for the Continuous Monitoring service

type: application
version: 0.1.1
appVersion: "0.1.1"

keywords:
  - monitoring
  - observability
  - continuous

home: https://github.com/firasmosbehi/continuous-monitoring-chart
sources:
  - https://github.com/firasmosbehi/continuous-monitoring-chart

maintainers:
  - name: Firas Mosbehi
    email: firas.mosbehi@insat.ucar.tn

annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Initial chart release."
