apiVersion: v2
name: continuous-monitoring
description: Helm chart for the Continuous Monitoring service

type: application
version: 0.1.3
appVersion: "0.1.1"

keywords:
  - monitoring
  - observability
  - continuous

home: https://github.com/firasmosbehi/continuous-monitoring-chart
sources:
  - https://github.com/firasmosbehi/continuous-monitoring-chart

maintainers:
  - name: Firas Mosbehi
    email: firas.mosbehi@insat.ucar.tn

annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Add Promtail-based log collection, Loki datasource override, and Grafana logs dashboards."
  artifacthub.io/images: |
    - name: grafana
      image: grafana/grafana:10.4.2
    - name: prometheus
      image: prom/prometheus:v2.50.1
    - name: loki
      image: grafana/loki:2.9.5
    - name: promtail
      image: grafana/promtail:2.9.5
    - name: node-exporter
      image: quay.io/prometheus/node-exporter:v1.7.0
    - name: kube-state-metrics
      image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.10.1
