exporters:
  nodeExporter:
    enabled: true
    image:
      repository: quay.io/prometheus/node-exporter
      tag: master
      digest: sha256:5056097aa05bbb4dc22039cce8f2afa04d2a5223170d8d9b27b409955e3eb19d
      pullPolicy: IfNotPresent

  kubeStateMetrics:
    enabled: true
    image:
      repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
      tag: v2.18.0
      digest: sha256:1545919b72e3ae035454fc054131e8d0f14b42ef6fc5b2ad5c751cafa6b2130e
      pullPolicy: IfNotPresent

grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: "12.3.1"
    digest: sha256:2175aaa91c96733d86d31cf270d5310b278654b03f5718c59de12a865380a31f
    pullPolicy: IfNotPresent

datasources:
  enabled: true
  prometheus:
    enabled: true
    image:
      repository: prom/prometheus
      tag: v3.5.1
      digest: sha256:38c3b05c3bc744ff1b0b7b4eb82196026442845e62a1e2073795565da506d7a2
      pullPolicy: IfNotPresent
  loki:
    enabled: true
    image:
      repository: grafana/loki
      tag: "3.6.4"
      digest: sha256:be31579ac047e9f78b81e48f3b69d3af709e7299b431d5aa78bcda43382f9511
      pullPolicy: IfNotPresent
    url: ""

logs:
  promtail:
    enabled: true
    image:
      repository: grafana/promtail
      tag: "3.6.4"
      digest: sha256:ba2f727003e28541bf8a9b9ff92a8adbe5a48f1cfe388493f9266bbd94891fe3
      pullPolicy: IfNotPresent
    clientUrl: ""
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []

dashboards:
  enabled: true
