exporters:
  nodeExporter:
    enabled: true
    image:
      repository: quay.io/prometheus/node-exporter
      tag: v1.8.1
      pullPolicy: IfNotPresent

  kubeStateMetrics:
    enabled: true
    image:
      repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
      tag: v2.13.0
      pullPolicy: IfNotPresent

grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: "11.2.2"
    pullPolicy: IfNotPresent

datasources:
  enabled: true
  prometheus:
    enabled: true
    image:
      repository: prom/prometheus
      tag: v2.54.1
      pullPolicy: IfNotPresent
  loki:
    enabled: true
    image:
      repository: grafana/loki
      tag: "3.1.1"
      pullPolicy: IfNotPresent
    url: ""

logs:
  promtail:
    enabled: true
    image:
      repository: grafana/promtail
      tag: "3.1.1"
      pullPolicy: IfNotPresent
    clientUrl: ""
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []

dashboards:
  enabled: true
