{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "continuous-monitoring.fullname" . }}-grafana
  labels:
    {{- include "continuous-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - name: http
      port: {{ .Values.grafana.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "continuous-monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }}
