{{- if .Values.logs.promtail.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "continuous-monitoring.fullname" . }}-promtail
  labels:
    {{- include "continuous-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: promtail
    app.kubernetes.io/part-of: logs
spec:
  selector:
    matchLabels:
      {{- include "continuous-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: promtail
  template:
    metadata:
      labels:
        {{- include "continuous-monitoring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: promtail
    spec:
      serviceAccountName: {{ include "continuous-monitoring.fullname" . }}-promtail
      containers:
        - name: promtail
          image: "{{ include "continuous-monitoring.image" (list .Values.logs.promtail.image.repository .Values.logs.promtail.image.tag .Values.logs.promtail.image.digest) }}"
          imagePullPolicy: {{ .Values.logs.promtail.image.pullPolicy }}
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
          ports:
            - name: http
              containerPort: 3101
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
              readOnly: true
            - name: run
              mountPath: /run/promtail
            - name: varlog
              mountPath: /var/log
              readOnly: true
          {{- with .Values.logs.promtail.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "continuous-monitoring.fullname" . }}-promtail-config
        - name: run
          emptyDir: {}
        - name: varlog
          hostPath:
            path: /var/log
      {{- with .Values.logs.promtail.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.logs.promtail.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.logs.promtail.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
