{{- if and .Values.databases.postgres.enabled (not .Values.databases.postgres.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "continuous-monitoring.fullname" . }}-postgres-credentials
  labels:
    {{- include "continuous-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
    app.kubernetes.io/part-of: databases
type: Opaque
stringData:
  username: {{ .Values.databases.postgres.auth.username }}
  password: {{ .Values.databases.postgres.auth.password }}
  database: {{ .Values.databases.postgres.auth.database }}
  dsn: postgresql://{{ .Values.databases.postgres.auth.username }}:{{ .Values.databases.postgres.auth.password }}@127.0.0.1:{{ .Values.databases.postgres.service.port }}/{{ .Values.databases.postgres.auth.database }}?sslmode=disable
{{- end }}
